# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  # - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/**/*'
Style/SymbolProc:
  Exclude:
    - 'app/admin/**/*'

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'spec/**/*'
    - 'app/mailers/admin_mailer.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Style/Documentation:
  Enabled: false
